### ISSUE TITLE
separate nodes.js file into separate files

### ISSUE THREAD

**Issue by vipyne** [pipecat-ai/housecat#9]
see https://github.com/pipecat-ai/housecat/pull/6 for details/discussion.

**Comment by LucasMatuszewski** [comment]
Hey @vipyne @hyypeman - as we discussed in #6 - I reimplemented this without TypeScript and with minimal changes in code (only config.js for reusability and to start a standardization process):
https://github.com/pipecat-ai/housecat/pull/13

**Comment by hyypeman** [comment]
Thank you! Closing this
